import type {
  Expense,
  ShoppingItem,
  Task,
  BoardPost,
  CalendarEvent,
  BathroomReservation,
  DishwasherStatus,
} from '../types/app';

/**
 * Helper function to create mock data for a group
 * @param groupId - ID of the group
 * @param userId - ID of the current user
 * @param otherUsers - Array of other user IDs (default: ['user-2', 'user-3'])
 * @returns Object containing all mock data for the group
 */
export function createMockData(
  groupId: string,
  userId: string,
  otherUsers: string[] = ['user-2', 'user-3'],
): {
  expenses: Expense[];
  shoppingList: ShoppingItem[];
  tasks: Task[];
  boardPosts: BoardPost[];
  calendarEvents: CalendarEvent[];
  bathroomReservations: BathroomReservation[];
  dishwasherStatus: DishwasherStatus;
} {
  const allMembers = [userId, ...otherUsers];

  return {
    expenses: [
      // Bieżący miesiąc - ostatnie wydatki
      {
        id: 'exp-1',
        groupId,
        title: 'Zakupy spożywcze - Biedronka',
        amount: 234.50,
        paidBy: userId,
        splitBetween: allMembers,
        category: 'food',
        date: new Date(),
        description: 'Zakupy na cały tydzień',
      },
      {
        id: 'exp-2',
        groupId,
        title: 'Rachunki za prąd',
        amount: 180.00,
        paidBy: otherUsers[0] || userId,
        splitBetween: allMembers,
        category: 'utilities',
        date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-3',
        groupId,
        title: 'Internetowy + TV',
        amount: 99.00,
        paidBy: userId,
        splitBetween: allMembers,
        category: 'utilities',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        description: 'Abonament Orange',
      },
      {
        id: 'exp-4',
        groupId,
        title: 'Kino - Dune 2',
        amount: 75.00,
        paidBy: userId,
        splitBetween: [userId, otherUsers[0] || userId],
        category: 'entertainment',
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-5',
        groupId,
        title: 'Spotify Premium Family',
        amount: 29.99,
        paidBy: otherUsers[1] || userId,
        splitBetween: allMembers,
        category: 'entertainment',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-6',
        groupId,
        title: 'Gaz',
        amount: 145.30,
        paidBy: otherUsers[1] || userId,
        splitBetween: allMembers,
        category: 'utilities',
        date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-7',
        groupId,
        title: 'Woda i ścieki',
        amount: 87.50,
        paidBy: otherUsers[0] || userId,
        splitBetween: allMembers,
        category: 'utilities',
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-8',
        groupId,
        title: 'Zakupy spożywcze - Lidl',
        amount: 156.80,
        paidBy: otherUsers[0] || userId,
        splitBetween: allMembers,
        category: 'food',
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-9',
        groupId,
        title: 'Detergenty i proszek do prania',
        amount: 89.40,
        paidBy: userId,
        splitBetween: allMembers,
        category: 'shopping',
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-10',
        groupId,
        title: 'IKEA - nowe talerze i kubki',
        amount: 124.50,
        paidBy: otherUsers[0] || userId,
        splitBetween: allMembers,
        category: 'shopping',
        date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-11',
        groupId,
        title: 'Restauracja - sushi',
        amount: 189.00,
        paidBy: otherUsers[1] || userId,
        splitBetween: allMembers,
        category: 'food',
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-12',
        groupId,
        title: 'Kebab na wynos',
        amount: 42.00,
        paidBy: otherUsers[0] || userId,
        splitBetween: [otherUsers[0] || userId, otherUsers[1] || userId],
        category: 'food',
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      // Poprzedni miesiąc
      {
        id: 'exp-13',
        groupId,
        title: 'Netflix i Spotify',
        amount: 59.99,
        paidBy: otherUsers[1] || userId,
        splitBetween: allMembers,
        category: 'entertainment',
        date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        description: 'Subskrypcje miesięczne',
      },
      {
        id: 'exp-14',
        groupId,
        title: 'Pizza na wieczór filmowy',
        amount: 89.90,
        paidBy: userId,
        splitBetween: allMembers,
        category: 'food',
        date: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-15',
        groupId,
        title: 'Środki czystości',
        amount: 67.50,
        paidBy: otherUsers[0] || userId,
        splitBetween: allMembers,
        category: 'shopping',
        date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-16',
        groupId,
        title: 'Rachunki za prąd',
        amount: 165.00,
        paidBy: userId,
        splitBetween: allMembers,
        category: 'utilities',
        date: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-17',
        groupId,
        title: 'Internet',
        amount: 99.00,
        paidBy: otherUsers[0] || userId,
        splitBetween: allMembers,
        category: 'utilities',
        date: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-18',
        groupId,
        title: 'Zakupy spożywcze',
        amount: 198.50,
        paidBy: otherUsers[1] || userId,
        splitBetween: allMembers,
        category: 'food',
        date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-19',
        groupId,
        title: 'Zakupy spożywcze',
        amount: 145.20,
        paidBy: userId,
        splitBetween: allMembers,
        category: 'food',
        date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'exp-20',
        groupId,
        title: 'Koncert',
        amount: 150.00,
        paidBy: otherUsers[0] || userId,
        splitBetween: [userId, otherUsers[0] || userId],
        category: 'entertainment',
        date: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
      },
    ],
    shoppingList: [
      {
        id: 'shop-1',
        groupId,
        name: 'Mleko 2%',
        quantity: '2 litry',
        addedBy: otherUsers[0] || userId,
        purchased: false,
        estimatedPrice: 7.50,
        createdAt: new Date(),
      },
      {
        id: 'shop-2',
        groupId,
        name: 'Chleb',
        quantity: '2 sztuki',
        addedBy: userId,
        claimedBy: otherUsers[1] || userId,
        purchased: false,
        estimatedPrice: 9.00,
        createdAt: new Date(),
      },
      {
        id: 'shop-3',
        groupId,
        name: 'Papier toaletowy',
        quantity: '1 opakowanie (12 rolek)',
        addedBy: otherUsers[1] || userId,
        purchased: false,
        estimatedPrice: 24.99,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'shop-4',
        groupId,
        name: 'Pomidory',
        quantity: '1kg',
        addedBy: userId,
        purchased: false,
        estimatedPrice: 12.00,
        createdAt: new Date(),
      },
      {
        id: 'shop-5',
        groupId,
        name: 'Jajka',
        quantity: '10 sztuk',
        addedBy: otherUsers[0] || userId,
        purchased: false,
        estimatedPrice: 8.50,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'shop-6',
        groupId,
        name: 'Masło',
        quantity: '200g',
        addedBy: userId,
        claimedBy: userId,
        purchased: false,
        estimatedPrice: 6.99,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'shop-7',
        groupId,
        name: 'Makaron',
        quantity: '500g',
        addedBy: otherUsers[1] || userId,
        purchased: true,
        estimatedPrice: 4.50,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        id: 'shop-8',
        groupId,
        name: 'Sok pomarańczowy',
        quantity: '1 litr',
        addedBy: userId,
        purchased: true,
        estimatedPrice: 5.99,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
    ],
    tasks: [
      {
        id: 'task-1',
        groupId,
        title: 'Odkurzanie całego mieszkania',
        description: 'Pamiętaj o narożnikach i pod meblami',
        assignedTo: userId,
        frequency: 'weekly',
        completed: false,
        dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        rotationOrder: allMembers,
      },
      {
        id: 'task-2',
        groupId,
        title: 'Sprzątanie łazienki',
        assignedTo: otherUsers[0] || userId,
        frequency: 'weekly',
        completed: false,
        dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        rotationOrder: allMembers,
      },
      {
        id: 'task-3',
        groupId,
        title: 'Wyniesienie śmieci',
        assignedTo: otherUsers[1] || userId,
        frequency: 'daily',
        completed: false,
        dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        rotationOrder: allMembers,
      },
      {
        id: 'task-4',
        groupId,
        title: 'Mycie okien',
        assignedTo: userId,
        frequency: 'monthly',
        completed: false,
        dueDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
        rotationOrder: allMembers,
      },
      {
        id: 'task-5',
        groupId,
        title: 'Wymiana pościeli',
        assignedTo: otherUsers[0] || userId,
        frequency: 'weekly',
        completed: false,
        dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        rotationOrder: allMembers,
      },
      {
        id: 'task-6',
        groupId,
        title: 'Sprzątanie kuchni',
        assignedTo: otherUsers[1] || userId,
        frequency: 'daily',
        completed: false,
        dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        rotationOrder: allMembers,
      },
    ],
    boardPosts: [
      {
        id: 'post-1',
        groupId,
        authorId: otherUsers[0] || userId,
        title: 'Impreza w piątek! 🎉',
        content: 'Hej! W piątek wieczorem zorganizuję małe spotkanie z przyjaciółmi. Będzie nas około 8 osób. Postaram się nie robić za dużo hałasu po 22:00. Dajcie znać jeśli macie jakieś pytania!',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        comments: [
          {
            id: 'comment-1',
            authorId: userId,
            content: 'Super! Mogę coś przynieść?',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000),
          },
          {
            id: 'comment-2',
            authorId: otherUsers[1] || userId,
            content: 'Brzmi świetnie, miłej zabawy! 🎊',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
          },
        ],
      },
      {
        id: 'post-2',
        groupId,
        authorId: otherUsers[1] || userId,
        title: 'Naprawa pralki w środę',
        content: 'Przyjedzie serwisant w środę między 14:00 a 16:00. Ktoś będzie w domu?',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        comments: [
          {
            id: 'comment-3',
            authorId: userId,
            content: 'Ja mogę być, pracuję zdalnie tego dnia',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000),
          },
        ],
      },
      {
        id: 'post-3',
        groupId,
        authorId: userId,
        title: 'Nowy sklep w okolicy',
        content: 'Otworzyła się nowa Żabka naprzeciwko - mają promocje!',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        comments: [],
      },
      {
        id: 'post-4',
        groupId,
        authorId: userId,
        title: 'Spotkanie mieszkaniowe',
        content: 'Czy możemy się spotkać w sobotę wieczorem? Chciałbym omówić sprawy związane z mieszkaniem.',
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        comments: [
          {
            id: 'comment-4',
            authorId: otherUsers[0] || userId,
            content: 'Oczywiście! Która godzina?',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
          },
        ],
      },
    ],
    calendarEvents: [
      {
        id: 'event-1',
        groupId,
        title: 'Wyjazd do rodziny',
        type: 'absence',
        userId: otherUsers[0] || userId,
        startDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
        description: 'Wracam w niedzielę wieczorem',
      },
      {
        id: 'event-2',
        groupId,
        title: 'Remont łazienki',
        type: 'event',
        userId: userId,
        startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000),
        description: 'Hydraulik będzie wymieniał baterie',
      },
      {
        id: 'event-3',
        groupId,
        title: 'Weekend na wsi',
        type: 'absence',
        userId: userId,
        startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        description: 'Wracam w niedzielę',
      },
      {
        id: 'event-4',
        groupId,
        title: 'Urodziny kolegi',
        type: 'event',
        userId: otherUsers[1] || userId,
        startDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        description: 'Impreza urodzinowa',
      },
      {
        id: 'event-5',
        groupId,
        title: 'Wyjazd służbowy',
        type: 'absence',
        userId: otherUsers[1] || userId,
        startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        description: 'Powrót wczoraj',
      },
    ],
    bathroomReservations: [
      {
        id: 'bath-1',
        groupId,
        userId: otherUsers[0] || userId,
        startTime: new Date(Date.now() + 60 * 60 * 1000),
        endTime: new Date(Date.now() + 90 * 60 * 1000),
        occupied: false,
      },
      {
        id: 'bath-2',
        groupId,
        userId: userId,
        startTime: new Date(Date.now() + 3 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 3.5 * 60 * 60 * 1000),
        occupied: false,
      },
      {
        id: 'bath-3',
        groupId,
        userId: otherUsers[1] || userId,
        startTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 24 * 60 * 60 * 1000 + 45 * 60 * 1000),
        occupied: false,
      },
    ],
    dishwasherStatus: {
      groupId,
      status: 'loading',
      contributors: [userId, otherUsers[1] || userId],
    },
  };
}

