import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    gradient: {
      flex: 1,
      justifyContent: 'center',
    },
    flex: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 24,
      paddingVertical: 48,
      justifyContent: 'center',
    },
    centerBox: {
      alignItems: 'center',
      gap: 24,
    },
    heroIcon: {
      width: 80,
      height: 80,
      borderRadius: 24,
      backgroundColor: '#3b82f6',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
    },
    title: {
      fontSize: 28,
      fontWeight: '700',
      color: '#1f2937',
    },
    subtitle: {
      fontSize: 16,
      color: '#4b5563',
    },
    actions: {
      width: '100%',
      gap: 16,
    },
    buttonContentPrimary: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    buttonTextPrimary: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '600',
    },
    buttonContentGhost: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    whiteGhostButton: {
      backgroundColor: '#FFFFFF',
    },
    buttonTextGhost: {
      fontSize: 16,
      fontWeight: '600',
    },
    cardContent: {
      gap: 16,
    },
    joinCard: {
      width: '100%',
      borderRadius: 24,
      paddingVertical: 8,
      paddingHorizontal: 4,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 12,
    },
    joinCardContent: {
      gap: 16,
      paddingTop: 8,
    },
    createCard: {
      width: '100%',
      borderRadius: 28,
      borderWidth: 1,
      borderColor: '#e5e7eb',
      backgroundColor: '#ffffff',
      paddingHorizontal: 12,
      paddingVertical: 16,
      shadowColor: '#1f2937',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.05,
      shadowRadius: 20,
      elevation: 8,
    },
    createHeader: {
      gap: 8,
    },
    createTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: '#111827',
    },
    createDescription: {
      fontSize: 16,
      color: '#6b7280',
    },
    createContent: {
      gap: 24,
    },
    joinTitle: {
      fontSize: 22,
      fontWeight: '700',
    },
    joinDescription: {
      fontSize: 16,
      color: '#6b7280',
    },
    inputWrapper: {
      gap: 8,
    },
    error: {
      color: '#dc2626',
      fontSize: 13,
      marginTop: 4,
    },
    textInput: {
      backgroundColor: '#f4f4f5',
      borderRadius: 16,
      borderWidth: 0,
      paddingVertical: 16,
      fontSize: 16,
      padding: 22,
    },
    label: {
      fontSize: 14,
      color: '#4b5563',
    },
    fullWidthButton: {
      width: '100%',
      borderRadius: 18,
      height: 56,
    },
    fullWidthColumn: {
      width: '100%',
      gap: 12,
    },
    primaryButton: {
      backgroundColor: '#155DFC',
    },
    secondaryButton: {
      borderWidth: 1,
      borderColor: '#d1d5db',
    },
    cardHeaderCenter: {
      alignItems: 'center',
      gap: 4,
    },
    codeBox: {
      width: '100%',
      backgroundColor: '#e3edff',
      borderRadius: 20,
      paddingVertical: 18,
      paddingHorizontal: 20,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#c6d7ff',
    },
    codeLabel: {
      fontSize: 13,
      color: '#4b5563',
      marginBottom: 6,
    },
    codeValue: {
      fontSize: 36,
      letterSpacing: 8,
      fontWeight: '700',
      color: '#1d4ed8',
      fontFamily: 'monospace',
    },
    infoText: {
      fontSize: 13,
      color: '#4b5563',
      textAlign: 'center',
    },
    buttonColumn: {
      flexDirection: 'column',
      gap: 12,
    },
    halfButton: {
      flex: 1,
    },
    codeInput: {
      fontSize: 24,
      letterSpacing: 6,
      fontWeight: '600',
      backgroundColor: '#f3f4f6',
      borderWidth: 1,
      borderColor: '#e5e7eb',
      borderRadius: 12,
      paddingVertical: 12,
    },
    qrCard: {
      width: '100%',
      borderRadius: 28,
      paddingHorizontal: 20,
      paddingVertical: 28,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 14,
    },
    qrCardContent: {
      alignItems: 'center',
      gap: 24,
    },
    qrImageWrapper: {
      padding: 12,
      borderRadius: 20,
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e5e7eb',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.05,
      shadowRadius: 16,
      elevation: 8,
    },
    qrTextGroup: {
      alignItems: 'center',
      gap: 6,
    },
    qrTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: '#111827',
    },
    qrSubtitle: {
      fontSize: 15,
      color: '#6b7280',
      textAlign: 'center',
    },
    qrButton: {
      alignSelf: 'stretch',
      borderRadius: 18,
      height: 56,
    },
  }) as Record<string, any>;